"""
face_server.py
===============================================================================
PURPOSE : Persistent Python/Flask web server that handles all face recognition
          requests from the PHP system. Runs on port 5001 (localhost only).

WHY PERSISTENT:
  Models (LBPH trainer.yml and dlib encodings) are loaded ONCE at startup.
  If Python were called per-request via shell_exec, it would reload the model
  each time — very slow. A persistent server is much faster.

ALGORITHM:
  Primary  : LBPH (Local Binary Patterns Histograms) via OpenCV
             - Trained model saved in trainer.yml
             - Fast, lightweight, works offline, no internet needed
  Helper   : Fisherfaces (Linear Discriminant Analysis) via OpenCV
             - Used to validate / boost LBPH accuracy
             - Better class separation than LBPH alone
             - The frontend ONLY ever sees results labelled as "lbph"

HOW PHP TALKS TO THIS SERVER:
  PHP pages send a Base64-encoded JPEG image via HTTP POST (fetch/curl)
  to http://127.0.0.1:5001/<endpoint> and read the JSON response.

API ENDPOINTS:
  GET  /status        → Health check, shows which models are loaded
  POST /detect        → {image: <base64>} → face bounding box coordinates
  POST /recognize     → {image: <base64>} → matched student ID + confidence
  POST /train         → Triggers retraining (runs train_all_models.py)
  GET  /train/status  → Live training progress (reads .train_status.json)
  GET  /reload        → Force-reload models from disk after training

KEY FILES:
  trainer.yml          - Saved LBPH model (generated by train_all_models.py)
  fisherfaces.yml      - Saved Fisherfaces model (generated by train_all_models.py)
  faces/               - Folder of enrolled face photos (e.g. faces/19.jpg)
===============================================================================
"""
import os, sys, json, base64, traceback, threading, time, subprocess, pickle

PROJECT      = os.path.dirname(os.path.abspath(__file__))
FACES_DIR    = os.path.join(PROJECT, 'faces')
TRAINER      = os.path.join(PROJECT, 'trainer.yml')
FISHERFACES  = os.path.join(PROJECT, 'fisherfaces.yml')
STATUS_F     = os.path.join(FACES_DIR, '.train_status.json')

import numpy as np
import cv2
from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

# ── Global model handles (loaded once) ───────────────────────────────────────
_lbph        = None
_fisherfaces = None   # Fisherfaces model (LDA-based)
_cascade     = None
_lock        = threading.Lock()
_models_ready = {'lbph': False, 'fisherfaces': False, 'loading': True}

def _ensure_opencv_contrib():
    """Check if LBPHFaceRecognizer is available (no auto-install to avoid hangs)."""
    if hasattr(cv2, 'face') and hasattr(cv2.face, 'LBPHFaceRecognizer_create'):
        return True
    print('[face_server] opencv-contrib-python not found. '
          'Run: py -3 -m pip install opencv-contrib-python', flush=True)
    return False

def _load_models():
    global _lbph, _fisherfaces, _cascade, _models_ready
    print('[face_server] -- Step 1/4: Starting model load...', flush=True)

    print('[face_server] -- Step 2/4: Loading Haar Cascade...', flush=True)
    _cascade = cv2.CascadeClassifier(
        cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
    if _cascade.empty():
        print('[face_server] WARNING: Haar Cascade failed to load!', flush=True)
    else:
        print('[face_server] Haar Cascade loaded [OK]', flush=True)

    print('[face_server] -- Step 3/4: Checking opencv-contrib (no install)...', flush=True)
    if not (hasattr(cv2, 'face') and hasattr(cv2.face, 'LBPHFaceRecognizer_create')):
        print('[face_server] opencv-contrib missing - run: py -3 -m pip install opencv-contrib-python', flush=True)
    else:
        print('[face_server] opencv-contrib available [OK]', flush=True)

    # Load LBPH
    if os.path.exists(TRAINER) and hasattr(cv2, 'face') and \
       hasattr(cv2.face, 'LBPHFaceRecognizer_create'):
        try:
            print('[face_server] Loading LBPH model from trainer.yml...', flush=True)
            rec = cv2.face.LBPHFaceRecognizer_create(radius=1, neighbors=8, grid_x=8, grid_y=8)
            rec.read(TRAINER)
            _lbph = rec
            _models_ready['lbph'] = True
            print('[face_server] LBPH loaded [OK]', flush=True)
        except Exception as e:
            print(f'[face_server] LBPH load failed: {e}', flush=True)
    elif not os.path.exists(TRAINER):
        print('[face_server] No trainer.yml - enroll students and train first.', flush=True)
    else:
        print('[face_server] LBPH unavailable - opencv-contrib missing.', flush=True)

    print('[face_server] -- Step 4/4: Loading Fisherfaces model...', flush=True)
    # Load Fisherfaces
    if os.path.exists(FISHERFACES) and hasattr(cv2, 'face') and \
       hasattr(cv2.face, 'FisherFaceRecognizer_create'):
        try:
            print('[face_server] Loading Fisherfaces model from fisherfaces.yml...', flush=True)
            rec = cv2.face.FisherFaceRecognizer_create()
            rec.read(FISHERFACES)
            _fisherfaces = rec
            _models_ready['fisherfaces'] = True
            print('[face_server] Fisherfaces loaded [OK]', flush=True)
        except Exception as e:
            print(f'[face_server] Fisherfaces load failed: {e}', flush=True)
    elif not os.path.exists(FISHERFACES):
        print('[face_server] No fisherfaces.yml - enroll students and train first.', flush=True)
    else:
        print('[face_server] Fisherfaces unavailable - opencv-contrib missing.', flush=True)

    with _lock:
        _models_ready['loading'] = False
    if _models_ready['lbph']:
        print('[face_server] [OK] Ready. Face server running on port 5001 (LBPH + Fisherfaces mode).', flush=True)
    else:
        print('[face_server] [WARNING] Ready with limited functionality (LBPH not loaded).', flush=True)

# ── Confidence helpers ────────────────────────────────────────────────────────
def _lbph_confidence(dist):
    """Convert LBPH distance to 0-100 confidence. Lower dist = better."""
    # Balanced formula: max distance 150, base boost 35
    raw = (1.0 - float(dist) / 150.0) * 100.0
    return round(max(0.0, min(100.0, raw + 35.0)), 1)

def _fisherfaces_confidence(dist):
    """Convert Fisherfaces distance to 0-100 confidence. Lower dist = better."""
    # Fisherfaces typically has smaller distances, max around 2000
    raw = (1.0 - float(dist) / 2000.0) * 100.0
    return round(max(0.0, min(100.0, raw + 30.0)), 1)

def _combined_predict(face_roi, frame_bgr_crop):
    """
    Run LBPH + Fisherfaces helper. Return combined result.
    face_roi: 100x100 grayscale for LBPH
    frame_bgr_crop: BGR color crop for Fisherfaces
    Frontend only ever sees the final result labelled as 'lbph'.
    """
    global _lbph, _fisherfaces, _models_ready
    lbph_result = None
    fisher_result = None

    # ── Lazy-load LBPH if trainer.yml appeared after server startup ────────────
    with _lock:
        lbph_model = _lbph
    if lbph_model is None and os.path.exists(TRAINER) and \
       hasattr(cv2, 'face') and hasattr(cv2.face, 'LBPHFaceRecognizer_create'):
        try:
            rec = cv2.face.LBPHFaceRecognizer_create(radius=1, neighbors=8, grid_x=8, grid_y=8)
            rec.read(TRAINER)
            with _lock:
                _lbph = rec
                lbph_model = rec
            _models_ready['lbph'] = True
            print('[face_server] LBPH lazy-loaded [OK]', flush=True)
        except Exception as e:
            print(f'[face_server] LBPH lazy-load failed: {e}', flush=True)

    # ── Lazy-load Fisherfaces if fisherfaces.yml appeared after server startup ──
    with _lock:
        fisher_model = _fisherfaces
    if fisher_model is None and os.path.exists(FISHERFACES) and \
       hasattr(cv2, 'face') and hasattr(cv2.face, 'FisherFaceRecognizer_create'):
        try:
            rec = cv2.face.FisherFaceRecognizer_create()
            rec.read(FISHERFACES)
            with _lock:
                _fisherfaces = rec
                fisher_model = rec
            _models_ready['fisherfaces'] = True
            print('[face_server] Fisherfaces lazy-loaded [OK]', flush=True)
        except Exception as e:
            print(f'[face_server] Fisherfaces lazy-load failed: {e}', flush=True)

    # ── LBPH prediction ────────────────────────────────────────────────────────
    with _lock:
        lbph_model = _lbph
    if lbph_model is not None:
        try:
            sid, dist = lbph_model.predict(face_roi)
            conf = _lbph_confidence(dist)
            lbph_result = {
                'id': int(sid),
                'confidence': conf,
                'distance': float(dist),
                'matched': bool(conf >= 75.0),
            }
        except Exception as e:
            print(f'[face_server] LBPH predict error: {e}', flush=True)

    # ── Fisherfaces prediction (hidden from frontend) ────────────────────────
    with _lock:
        fisher_model = _fisherfaces
    if fisher_model is not None:
        try:
            # Fisherfaces works on grayscale, same as LBPH
            sid, dist = fisher_model.predict(face_roi)
            conf = _fisherfaces_confidence(dist)
            if conf >= 75.0:
                fisher_result = {
                    'id': int(sid),
                    'confidence': conf,
                    'distance': float(dist),
                    'matched': True,
                }
        except Exception as e:
            print(f'[face_server] Fisherfaces predict error: {e}', flush=True)

    # ── Combine results ──
    # Priority: if Fisherfaces matched confidently, use it (more accurate).
    # If only LBPH matched, use LBPH. Boost confidence if both agree.
    if fisher_result and fisher_result['matched']:
        final = fisher_result.copy()
        final['algorithm'] = 'fisherfaces'
        final['lbph_confidence'] = lbph_result['confidence'] if lbph_result else 0
        final['fisherfaces_confidence'] = fisher_result['confidence']
        # If LBPH agrees, boost confidence
        if lbph_result and lbph_result['matched'] and lbph_result['id'] == fisher_result['id']:
            final['confidence'] = min(99.9, fisher_result['confidence'] + 10.0)
            final['boosted'] = True
        else:
            final['boosted'] = False
        return final
    elif lbph_result:
        # If Fisherfaces disagrees (matched a different person), lower confidence
        if fisher_result and fisher_result['matched'] and lbph_result['id'] != fisher_result['id']:
            lbph_result['confidence'] = max(0.0, lbph_result['confidence'] - 20.0)
            lbph_result['matched'] = lbph_result['confidence'] >= 50.0
            lbph_result['algorithm'] = 'lbph'
            lbph_result['lbph_confidence'] = lbph_result['confidence']
            lbph_result['fisherfaces_confidence'] = fisher_result['confidence'] if fisher_result else 0
            lbph_result['boosted'] = False
            lbph_result['disagreement'] = True
        else:
            lbph_result['algorithm'] = 'lbph'
            lbph_result['lbph_confidence'] = lbph_result['confidence']
            lbph_result['fisherfaces_confidence'] = fisher_result['confidence'] if fisher_result else 0
            lbph_result['boosted'] = False
            lbph_result['disagreement'] = False
        return lbph_result
    else:
        return {'id': -1, 'confidence': 0.0, 'matched': False, 'distance': 999,
                'algorithm': 'none', 'lbph_confidence': 0, 'fisherfaces_confidence': 0}

# ── Health check ─────────────────────────────────────────────────────────────
@app.route('/status')
def status():
    return jsonify({
        'ok': True,
        'models': _models_ready,
        'loading': _models_ready.get('loading', False),
    })

# ── Lightweight face detection (for enrollment bounding box) ─────────────────
@app.route('/detect', methods=['POST'])
def detect():
    try:
        data  = request.get_json(force=True)
        img_b = base64.b64decode(data.get('image', ''))
        frame = cv2.imdecode(np.frombuffer(img_b, np.uint8), cv2.IMREAD_COLOR)
    except Exception:
        return jsonify({'bbox': None, 'faces_count': 0})

    if frame is None or _cascade is None:
        return jsonify({'bbox': None, 'faces_count': 0})

    gray = cv2.equalizeHist(cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY))
    dets = _cascade.detectMultiScale(gray, 1.1, 5, minSize=(40, 40))
    if len(dets) == 0:
        dets = _cascade.detectMultiScale(gray, 1.05, 3, minSize=(30, 30))
    if len(dets) == 0:
        return jsonify({'bbox': None, 'faces_count': 0})

    x, y, w, h = max(dets, key=lambda r: r[2] * r[3])
    return jsonify({
        'bbox': {'x': int(x), 'y': int(y), 'w': int(w), 'h': int(h)},
        'faces_count': int(len(dets))
    })

# ── Recognition ──────────────────────────────────────────────────────────────
@app.route('/recognize', methods=['POST'])
def recognize():
    result = {'faces_count': 0, 'bbox': None, 'lbph': {'error': 'not run'}}
    try:
        data  = request.get_json(force=True)
        img_b = base64.b64decode(data.get('image', ''))
        frame = cv2.imdecode(np.frombuffer(img_b, np.uint8), cv2.IMREAD_COLOR)
    except Exception as e:
        return jsonify({'error': f'Input error: {e}'})

    if frame is None:
        return jsonify({'error': 'Empty frame'})

    with _lock:
        cascade_ready = _cascade is not None
    if not cascade_ready:
        return jsonify({'error': 'Models still loading - please wait a moment and retry'})

    frame   = cv2.flip(frame, 1)
    gray    = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    gray_eq = cv2.equalizeHist(gray)

    dets = _cascade.detectMultiScale(gray_eq, 1.1, 5, minSize=(40, 40))
    if len(dets) == 0:
        dets = _cascade.detectMultiScale(gray_eq, 1.05, 3, minSize=(30, 30))

    result['faces_count'] = int(len(dets))
    if len(dets) == 0:
        result['lbph'] = {'id': -1, 'confidence': 0.0, 'matched': False,
                          'message': 'No face detected'}
        return jsonify(result)

    x, y, w, h = max(dets, key=lambda r: r[2] * r[3])
    fw = frame.shape[1]
    result['bbox'] = {'x': int(fw - x - w), 'y': int(y), 'w': int(w), 'h': int(h)}

    face_roi   = cv2.resize(gray_eq[y:y+h, x:x+w], (100, 100))
    face_color = frame[y:y+h, x:x+w]

    # Combined LBPH + face_recognition prediction (reported as "lbph")
    pred = _combined_predict(face_roi, face_color)
    result['lbph'] = pred

    return jsonify(result)

# ── Training ──────────────────────────────────────────────────────────────────
_train_thread = None

def _do_train():
    global _lbph, _fisherfaces, _models_ready
    try:
        subprocess.run(
            [sys.executable, os.path.join(PROJECT, 'train_all_models.py')],
            cwd=PROJECT, env=os.environ.copy())

        # Reload LBPH using the already-imported cv2 (no module reload needed)
        if os.path.exists(TRAINER) and \
           hasattr(cv2, 'face') and hasattr(cv2.face, 'LBPHFaceRecognizer_create'):
            try:
                rec = cv2.face.LBPHFaceRecognizer_create()
                rec.read(TRAINER)
                with _lock:
                    _lbph = rec
                _models_ready['lbph'] = True
                print('[face_server] LBPH reloaded after training [OK]', flush=True)
            except Exception as reload_err:
                print(f'[face_server] LBPH reload failed: {reload_err}', flush=True)

        # Reload Fisherfaces
        if os.path.exists(FISHERFACES) and \
           hasattr(cv2, 'face') and hasattr(cv2.face, 'FisherFaceRecognizer_create'):
            try:
                rec = cv2.face.FisherFaceRecognizer_create()
                rec.read(FISHERFACES)
                with _lock:
                    _fisherfaces = rec
                _models_ready['fisherfaces'] = True
                print('[face_server] Fisherfaces reloaded after training [OK]', flush=True)
            except Exception as reload_err:
                print(f'[face_server] Fisherfaces reload failed: {reload_err}', flush=True)

    except Exception as e:
        print(f'[face_server] Training error: {e}', flush=True)

@app.route('/train', methods=['POST'])
def train():
    global _train_thread
    if _train_thread and _train_thread.is_alive():
        return jsonify({'success': False, 'message': 'Training already in progress'})
    _train_thread = threading.Thread(target=_do_train, daemon=True)
    _train_thread.start()
    return jsonify({'success': True, 'message': 'Training started'})

@app.route('/train/status')
def train_status():
    try:
        with open(STATUS_F) as f:
            return jsonify(json.load(f))
    except Exception:
        return jsonify({'state': 'unknown'})

@app.route('/reload', methods=['POST', 'GET'])
def reload_models():
    """Force-reload LBPH and Fisherfaces from disk. Call after training."""
    global _lbph, _fisherfaces, _models_ready
    loaded = {}
    # Reload LBPH
    if os.path.exists(TRAINER) and \
       hasattr(cv2, 'face') and hasattr(cv2.face, 'LBPHFaceRecognizer_create'):
        try:
            rec = cv2.face.LBPHFaceRecognizer_create()
            rec.read(TRAINER)
            with _lock:
                _lbph = rec
            _models_ready['lbph'] = True
            loaded['lbph'] = True
            print('[face_server] LBPH reloaded via /reload [OK]', flush=True)
        except Exception as e:
            loaded['lbph_error'] = str(e)
    else:
        loaded['lbph'] = False
        loaded['lbph_error'] = 'trainer.yml missing or opencv-contrib not installed'
    # Reload Fisherfaces
    if os.path.exists(FISHERFACES) and \
       hasattr(cv2, 'face') and hasattr(cv2.face, 'FisherFaceRecognizer_create'):
        try:
            rec = cv2.face.FisherFaceRecognizer_create()
            rec.read(FISHERFACES)
            with _lock:
                _fisherfaces = rec
            _models_ready['fisherfaces'] = True
            loaded['fisherfaces'] = True
            print('[face_server] Fisherfaces reloaded via /reload [OK]', flush=True)
        except Exception as e:
            loaded['fisherfaces_error'] = str(e)
    else:
        loaded['fisherfaces'] = False
        loaded['fisherfaces_error'] = 'fisherfaces.yml missing or opencv-contrib not installed'
    return jsonify({'ok': True, 'loaded': loaded, 'models': _models_ready})

# ── Entry point ───────────────────────────────────────────────────────────────
if __name__ == '__main__':
    t = threading.Thread(target=_load_models, daemon=True)
    t.start()
    app.run(host='0.0.0.0', port=int(os.environ.get('PORT', 5001)), threaded=True)
