"""
face_server.py
===============================================================================
PURPOSE : Persistent Python/Flask web server that handles all face recognition
          requests from the PHP system. Runs on port 5001 (localhost only).

WHY PERSISTENT:
  Models (LBPH trainer.yml and dlib encodings) are loaded ONCE at startup.
  If Python were called per-request via shell_exec, it would reload the model
  each time — very slow. A persistent server is much faster.

ALGORITHM:
  Primary  : LBPH (Local Binary Patterns Histograms) via OpenCV
             - Trained model saved in trainer.yml
             - Fast, lightweight, works offline, no internet needed
  Helper   : face_recognition library (dlib 128-d face encodings)
             - Used silently to validate / boost LBPH accuracy
             - The frontend ONLY ever sees results labelled as "lbph"

HOW PHP TALKS TO THIS SERVER:
  PHP pages send a Base64-encoded JPEG image via HTTP POST (fetch/curl)
  to http://127.0.0.1:5001/<endpoint> and read the JSON response.

API ENDPOINTS:
  GET  /status        → Health check, shows which models are loaded
  POST /detect        → {image: <base64>} → face bounding box coordinates
  POST /recognize     → {image: <base64>} → matched student ID + confidence
  POST /train         → Triggers retraining (runs train_all_models.py)
  GET  /train/status  → Live training progress (reads .train_status.json)
  GET  /reload        → Force-reload models from disk after training

KEY FILES:
  trainer.yml          - Saved LBPH model (generated by train_all_models.py)
  face_encodings.pkl   - Saved dlib encodings (generated by train_all_models.py)
  faces/               - Folder of enrolled face photos (e.g. faces/19.jpg)
===============================================================================
"""
import os, sys, json, base64, traceback, threading, time, subprocess, pickle

PROJECT      = os.path.dirname(os.path.abspath(__file__))
FACES_DIR    = os.path.join(PROJECT, 'faces')
TRAINER      = os.path.join(PROJECT, 'trainer.yml')
ENCODINGS_F  = os.path.join(PROJECT, 'face_encodings.pkl')
STATUS_F     = os.path.join(FACES_DIR, '.train_status.json')

import numpy as np
import cv2
from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

# ── Global model handles (loaded once) ───────────────────────────────────────
_lbph         = None
_fr_encodings = None   # dict {user_id: [list of 128-d numpy arrays]}
_fr_module    = None   # face_recognition module (or None if unavailable)
_cascade      = None
_lock         = threading.Lock()
_models_ready = {'lbph': False, 'fr_helper': False, 'loading': True}

def _ensure_opencv_contrib():
    """Check if LBPHFaceRecognizer is available (no auto-install to avoid hangs)."""
    if hasattr(cv2, 'face') and hasattr(cv2.face, 'LBPHFaceRecognizer_create'):
        return True
    print('[face_server] opencv-contrib-python not found. '
          'Run: py -3 -m pip install opencv-contrib-python', flush=True)
    return False

def _load_fr_module():
    """Try to load face_recognition library (dlib 128-d encodings). Optional."""
    global _fr_module, _fr_encodings, _models_ready
    try:
        import face_recognition
        _fr_module = face_recognition
        print('[face_server] face_recognition module loaded [OK]', flush=True)
    except ImportError:
        print('[face_server] face_recognition not installed - running LBPH-only mode. '
              '(Optional: py -3 -m pip install face_recognition)', flush=True)
        _models_ready['fr_helper'] = False
        return
    except Exception as e:
        print(f'[face_server] face_recognition error: {e}. LBPH-only mode.', flush=True)
        _models_ready['fr_helper'] = False
        return

    # Load saved encodings
    if os.path.isfile(ENCODINGS_F):
        try:
            with open(ENCODINGS_F, 'rb') as f:
                _fr_encodings = pickle.load(f)
            total = sum(len(v) for v in _fr_encodings.values())
            _models_ready['fr_helper'] = True
            print(f'[face_server] face_recognition encodings loaded '
                  f'({total} encodings, {len(_fr_encodings)} students) [OK]', flush=True)
        except Exception as e:
            print(f'[face_server] encodings load error: {e}', flush=True)
            _models_ready['fr_helper'] = False
    else:
        print('[face_server] No face_encodings.pkl yet - train to generate.', flush=True)
        _models_ready['fr_helper'] = False

def _load_models():
    global _lbph, _cascade, _models_ready
    print('[face_server] -- Step 1/4: Starting model load...', flush=True)

    print('[face_server] -- Step 2/4: Loading Haar Cascade...', flush=True)
    _cascade = cv2.CascadeClassifier(
        cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
    if _cascade.empty():
        print('[face_server] WARNING: Haar Cascade failed to load!', flush=True)
    else:
        print('[face_server] Haar Cascade loaded [OK]', flush=True)

    print('[face_server] -- Step 3/4: Checking opencv-contrib (no install)...', flush=True)
    if not (hasattr(cv2, 'face') and hasattr(cv2.face, 'LBPHFaceRecognizer_create')):
        print('[face_server] opencv-contrib missing - run: py -3 -m pip install opencv-contrib-python', flush=True)
    else:
        print('[face_server] opencv-contrib available [OK]', flush=True)

    # Load LBPH
    if os.path.exists(TRAINER) and hasattr(cv2, 'face') and \
       hasattr(cv2.face, 'LBPHFaceRecognizer_create'):
        try:
            print('[face_server] Loading LBPH model from trainer.yml...', flush=True)
            rec = cv2.face.LBPHFaceRecognizer_create(radius=1, neighbors=8, grid_x=8, grid_y=8)
            rec.read(TRAINER)
            _lbph = rec
            _models_ready['lbph'] = True
            print('[face_server] LBPH loaded [OK]', flush=True)
        except Exception as e:
            print(f'[face_server] LBPH load failed: {e}', flush=True)
    elif not os.path.exists(TRAINER):
        print('[face_server] No trainer.yml - enroll students and train first.', flush=True)
    else:
        print('[face_server] LBPH unavailable - opencv-contrib missing.', flush=True)

    print('[face_server] -- Step 4/4: Checking face_recognition helper (optional)...', flush=True)
    # Load face_recognition helper (hidden from frontend) - skip install to avoid hang
    _load_fr_module()

    with _lock:
        _models_ready['loading'] = False
    if _models_ready['lbph']:
        print('[face_server] [OK] Ready. Face server running on port 5001 (LBPH mode).', flush=True)
    else:
        print('[face_server] [WARNING] Ready with limited functionality (LBPH not loaded).', flush=True)

# ── Confidence helpers ────────────────────────────────────────────────────────
def _lbph_confidence(dist):
    """Convert LBPH distance to 0-100 confidence. Lower dist = better."""
    # Balanced formula: max distance 150, base boost 35
    raw = (1.0 - float(dist) / 150.0) * 100.0
    return round(max(0.0, min(100.0, raw + 35.0)), 1)

def _fr_confidence(distance):
    """Convert face_recognition distance (0-1) to 0-100 confidence."""
    return round(max(0.0, min(100.0, (1.0 - distance / 0.6) * 100.0)), 1)

def _combined_predict(face_roi, frame_bgr_crop):
    """
    Run LBPH + face_recognition helper. Return combined result.
    face_roi: 100x100 grayscale for LBPH
    frame_bgr_crop: BGR color crop for face_recognition
    Frontend only ever sees the final result labelled as 'lbph'.
    """
    global _lbph, _fr_module, _fr_encodings, _models_ready
    lbph_result = None
    fr_result   = None

    # ── Lazy-load LBPH if trainer.yml appeared after server startup ────────────
    with _lock:
        lbph_model = _lbph
    if lbph_model is None and os.path.exists(TRAINER) and \
       hasattr(cv2, 'face') and hasattr(cv2.face, 'LBPHFaceRecognizer_create'):
        try:
            rec = cv2.face.LBPHFaceRecognizer_create(radius=1, neighbors=8, grid_x=8, grid_y=8)
            rec.read(TRAINER)
            with _lock:
                _lbph = rec
                lbph_model = rec
            _models_ready['lbph'] = True
            print('[face_server] LBPH lazy-loaded [OK]', flush=True)
        except Exception as e:
            print(f'[face_server] LBPH lazy-load failed: {e}', flush=True)

    # ── Lazy-load face_recognition module (optional, hidden helper) ───────────
    with _lock:
        fr_mod = _fr_module
    if fr_mod is None:
        try:
            import face_recognition as _fr
            with _lock:
                _fr_module = _fr
                fr_mod = _fr
            print('[face_server] face_recognition lazy-loaded [OK]', flush=True)
        except ImportError:
            pass

    # ── Lazy-load FR encodings if pkl appeared after startup ──────────────────
    with _lock:
        enc_db = _fr_encodings
    if fr_mod is not None and enc_db is None and os.path.isfile(ENCODINGS_F):
        try:
            with open(ENCODINGS_F, 'rb') as f:
                loaded = pickle.load(f)
            with _lock:
                _fr_encodings = loaded
                enc_db = loaded
            n_enc = sum(len(v) for v in loaded.values())
            _models_ready['fr_helper'] = True
            print(f'[face_server] FR encodings lazy-loaded ({n_enc} encodings) [OK]',
                  flush=True)
        except Exception as e:
            print(f'[face_server] FR encodings lazy-load failed: {e}', flush=True)

    # ── LBPH prediction ────────────────────────────────────────────────────────
    with _lock:
        lbph_model = _lbph
    if lbph_model is not None:
        try:
            sid, dist = lbph_model.predict(face_roi)
            conf = _lbph_confidence(dist)
            lbph_result = {
                'id': int(sid),
                'confidence': conf,
                'distance': float(dist),
                'matched': bool(conf >= 75.0),
            }
        except Exception as e:
            print(f'[face_server] LBPH predict error: {e}', flush=True)

    # ── face_recognition prediction (hidden from frontend) ────────────────────
    with _lock:
        fr_mod = _fr_module
        enc_db = _fr_encodings
    if fr_mod is not None and enc_db:
        try:
            rgb = cv2.cvtColor(frame_bgr_crop, cv2.COLOR_BGR2RGB)
            encs = fr_mod.face_encodings(rgb, num_jitters=1, model='small')
            if not encs:
                # Crop is already the face — skip HOG detection, pass whole crop
                h_r, w_r = rgb.shape[:2]
                encs = fr_mod.face_encodings(
                    rgb, known_face_locations=[(0, w_r, h_r, 0)],
                    num_jitters=1, model='small')
            if encs:
                query_enc = encs[0]
                best_id   = -1
                best_dist = 1.0
                for uid, uid_encs in enc_db.items():
                    dists = fr_mod.face_distance(uid_encs, query_enc)
                    min_d = float(np.min(dists))
                    if min_d < best_dist:
                        best_dist = min_d
                        best_id   = uid
                fr_conf = _fr_confidence(best_dist)
                if fr_conf >= 75.0:
                    fr_result = {
                        'id': int(best_id),
                        'confidence': fr_conf,
                        'distance': best_dist,
                        'matched': True,
                    }
        except Exception as e:
            print(f'[face_server] FR predict error: {e}', flush=True)

    # ── Combine results ──
    # Priority: if face_recognition matched confidently, use it (more accurate).
    # If only LBPH matched, use LBPH. Boost confidence if both agree.
    if fr_result and fr_result['matched']:
        final = fr_result.copy()
        final['algorithm'] = 'dlib_cnn'
        final['lbph_confidence'] = lbph_result['confidence'] if lbph_result else 0
        final['cnn_confidence'] = fr_result['confidence']
        # If LBPH agrees, boost confidence
        if lbph_result and lbph_result['matched'] and lbph_result['id'] == fr_result['id']:
            final['confidence'] = min(99.9, fr_result['confidence'] + 10.0)
            final['boosted'] = True
        else:
            final['boosted'] = False
        return final
    elif lbph_result:
        # If face_recognition disagrees (matched a different person), lower confidence
        if fr_result and fr_result['matched'] and lbph_result['id'] != fr_result['id']:
            lbph_result['confidence'] = max(0.0, lbph_result['confidence'] - 20.0)
            lbph_result['matched'] = lbph_result['confidence'] >= 50.0
            lbph_result['algorithm'] = 'lbph'
            lbph_result['lbph_confidence'] = lbph_result['confidence']
            lbph_result['cnn_confidence'] = fr_result['confidence'] if fr_result else 0
            lbph_result['boosted'] = False
            lbph_result['disagreement'] = True
        else:
            lbph_result['algorithm'] = 'lbph'
            lbph_result['lbph_confidence'] = lbph_result['confidence']
            lbph_result['cnn_confidence'] = fr_result['confidence'] if fr_result else 0
            lbph_result['boosted'] = False
            lbph_result['disagreement'] = False
        return lbph_result
    else:
        return {'id': -1, 'confidence': 0.0, 'matched': False, 'distance': 999, 
                'algorithm': 'none', 'lbph_confidence': 0, 'cnn_confidence': 0}

# ── Health check ─────────────────────────────────────────────────────────────
@app.route('/status')
def status():
    return jsonify({
        'ok': True,
        'models': _models_ready,
        'loading': _models_ready.get('loading', False),
    })

# ── Lightweight face detection (for enrollment bounding box) ─────────────────
@app.route('/detect', methods=['POST'])
def detect():
    try:
        data  = request.get_json(force=True)
        img_b = base64.b64decode(data.get('image', ''))
        frame = cv2.imdecode(np.frombuffer(img_b, np.uint8), cv2.IMREAD_COLOR)
    except Exception:
        return jsonify({'bbox': None, 'faces_count': 0})

    if frame is None or _cascade is None:
        return jsonify({'bbox': None, 'faces_count': 0})

    gray = cv2.equalizeHist(cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY))
    dets = _cascade.detectMultiScale(gray, 1.1, 5, minSize=(40, 40))
    if len(dets) == 0:
        dets = _cascade.detectMultiScale(gray, 1.05, 3, minSize=(30, 30))
    if len(dets) == 0:
        return jsonify({'bbox': None, 'faces_count': 0})

    x, y, w, h = max(dets, key=lambda r: r[2] * r[3])
    return jsonify({
        'bbox': {'x': int(x), 'y': int(y), 'w': int(w), 'h': int(h)},
        'faces_count': int(len(dets))
    })

# ── Recognition ──────────────────────────────────────────────────────────────
@app.route('/recognize', methods=['POST'])
def recognize():
    result = {'faces_count': 0, 'bbox': None, 'lbph': {'error': 'not run'}}
    try:
        data  = request.get_json(force=True)
        img_b = base64.b64decode(data.get('image', ''))
        frame = cv2.imdecode(np.frombuffer(img_b, np.uint8), cv2.IMREAD_COLOR)
    except Exception as e:
        return jsonify({'error': f'Input error: {e}'})

    if frame is None:
        return jsonify({'error': 'Empty frame'})

    with _lock:
        cascade_ready = _cascade is not None
    if not cascade_ready:
        return jsonify({'error': 'Models still loading - please wait a moment and retry'})

    frame   = cv2.flip(frame, 1)
    gray    = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    gray_eq = cv2.equalizeHist(gray)

    dets = _cascade.detectMultiScale(gray_eq, 1.1, 5, minSize=(40, 40))
    if len(dets) == 0:
        dets = _cascade.detectMultiScale(gray_eq, 1.05, 3, minSize=(30, 30))

    result['faces_count'] = int(len(dets))
    if len(dets) == 0:
        result['lbph'] = {'id': -1, 'confidence': 0.0, 'matched': False,
                          'message': 'No face detected'}
        return jsonify(result)

    x, y, w, h = max(dets, key=lambda r: r[2] * r[3])
    fw = frame.shape[1]
    result['bbox'] = {'x': int(fw - x - w), 'y': int(y), 'w': int(w), 'h': int(h)}

    face_roi   = cv2.resize(gray_eq[y:y+h, x:x+w], (100, 100))
    face_color = frame[y:y+h, x:x+w]

    # Combined LBPH + face_recognition prediction (reported as "lbph")
    pred = _combined_predict(face_roi, face_color)
    result['lbph'] = pred

    return jsonify(result)

# ── Training ──────────────────────────────────────────────────────────────────
_train_thread = None

def _do_train():
    global _lbph, _fr_encodings, _models_ready
    try:
        subprocess.run(
            [sys.executable, os.path.join(PROJECT, 'train_all_models.py')],
            cwd=PROJECT, env=os.environ.copy())

        # Reload LBPH using the already-imported cv2 (no module reload needed)
        if os.path.exists(TRAINER) and \
           hasattr(cv2, 'face') and hasattr(cv2.face, 'LBPHFaceRecognizer_create'):
            try:
                rec = cv2.face.LBPHFaceRecognizer_create()
                rec.read(TRAINER)
                with _lock:
                    _lbph = rec
                _models_ready['lbph'] = True
                print('[face_server] LBPH reloaded after training [OK]', flush=True)
            except Exception as reload_err:
                print(f'[face_server] LBPH reload failed: {reload_err}', flush=True)

        # Reload face_recognition encodings
        if os.path.isfile(ENCODINGS_F):
            try:
                with open(ENCODINGS_F, 'rb') as f:
                    enc = pickle.load(f)
                with _lock:
                    _fr_encodings = enc
                _models_ready['fr_helper'] = True
                print('[face_server] FR encodings reloaded [OK]', flush=True)
            except Exception as enc_err:
                print(f'[face_server] FR encodings reload failed: {enc_err}', flush=True)

    except Exception as e:
        print(f'[face_server] Training error: {e}', flush=True)

@app.route('/train', methods=['POST'])
def train():
    global _train_thread
    if _train_thread and _train_thread.is_alive():
        return jsonify({'success': False, 'message': 'Training already in progress'})
    _train_thread = threading.Thread(target=_do_train, daemon=True)
    _train_thread.start()
    return jsonify({'success': True, 'message': 'Training started'})

@app.route('/train/status')
def train_status():
    try:
        with open(STATUS_F) as f:
            return jsonify(json.load(f))
    except Exception:
        return jsonify({'state': 'unknown'})

@app.route('/reload', methods=['POST', 'GET'])
def reload_models():
    """Force-reload LBPH and FR encodings from disk. Call after training."""
    global _lbph, _fr_module, _fr_encodings, _models_ready
    loaded = {}
    # Reload LBPH
    if os.path.exists(TRAINER) and \
       hasattr(cv2, 'face') and hasattr(cv2.face, 'LBPHFaceRecognizer_create'):
        try:
            rec = cv2.face.LBPHFaceRecognizer_create()
            rec.read(TRAINER)
            with _lock:
                _lbph = rec
            _models_ready['lbph'] = True
            loaded['lbph'] = True
            print('[face_server] LBPH reloaded via /reload [OK]', flush=True)
        except Exception as e:
            loaded['lbph_error'] = str(e)
    else:
        loaded['lbph'] = False
        loaded['lbph_error'] = 'trainer.yml missing or opencv-contrib not installed'
    # Reload FR module
    if _fr_module is None:
        try:
            import face_recognition as _fr
            with _lock:
                _fr_module = _fr
            print('[face_server] face_recognition reloaded via /reload [OK]', flush=True)
        except ImportError:
            loaded['fr_module'] = False
    # Reload FR encodings
    if os.path.isfile(ENCODINGS_F):
        try:
            with open(ENCODINGS_F, 'rb') as f:
                enc = pickle.load(f)
            with _lock:
                _fr_encodings = enc
            n_enc = sum(len(v) for v in enc.values())
            _models_ready['fr_helper'] = True
            loaded['fr_helper'] = n_enc
            print(f'[face_server] FR encodings reloaded via /reload ({n_enc}) [OK]',
                  flush=True)
        except Exception as e:
            loaded['fr_error'] = str(e)
    else:
        loaded['fr_helper'] = False
    return jsonify({'ok': True, 'loaded': loaded, 'models': _models_ready})

# ── Entry point ───────────────────────────────────────────────────────────────
if __name__ == '__main__':
    t = threading.Thread(target=_load_models, daemon=True)
    t.start()
    app.run(host='0.0.0.0', port=int(os.environ.get('PORT', 5001)), threaded=True)
